# Name:     1_bsa.R
# Updated:  20191030
# User:     Andrew Kleist
# Figure:   Figure 1J

##### LOAD PACKAGES & SET WD ###################################################

  # load libraries, set wd
  library(tidyverse)
  library(ape)
  require(Biostrings)
  library(ggrepel)
  setwd("~/Desktop/Volkman_Lab/BABU_VOLKMAN/CHEMOKINE_PRJ/Data/kleist_2020/1_bsa")
  
  
##### ANALYSIS #################################################################
  
  # import (data generated by )
  data <- read_csv("input/site1site2.csv") # import, reformat
  
  # order
  order.ck <- as.factor(tolower(c("5uiw", "5wb2", "4xt1", "4rws","4ldo",
                                  "2n55","1ilp", "2mpm", "6fgp")))
  levels(data$pdb)
  data$pdb <- factor(data$pdb, levels = order.ck)
  
  # plot
  data %>%
    filter(code == "aa") %>%
    filter(type != "nmr" ) %>%
    filter(pdb != "4ldo" ) %>%
    ggplot(aes(pdb, bsa)) +
    geom_bar(stat="identity") +
    coord_cartesian(ylim=c(1000,1800)) +
    theme_minimal() 
  
  
  